-- 创建通勤打卡表
CREATE TABLE IF NOT EXISTS public.commute_checkins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  location_name TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  trigger_type TEXT
);

-- 添加注释
COMMENT ON TABLE public.commute_checkins IS '通勤打卡记录表';
COMMENT ON COLUMN public.commute_checkins.id IS '主键ID';
COMMENT ON COLUMN public.commute_checkins.created_at IS '打卡时间（UTC时区）';
COMMENT ON COLUMN public.commute_checkins.location_name IS '位置名称';
COMMENT ON COLUMN public.commute_checkins.latitude IS '纬度';
COMMENT ON COLUMN public.commute_checkins.longitude IS '经度';
COMMENT ON COLUMN public.commute_checkins.trigger_type IS '触发类型：上班/下班/未知';

-- 创建索引以优化查询性能
CREATE INDEX IF NOT EXISTS idx_commute_checkins_created_at ON public.commute_checkins(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_commute_checkins_trigger_type ON public.commute_checkins(trigger_type);

-- 启用行级安全策略（RLS）
ALTER TABLE public.commute_checkins ENABLE ROW LEVEL SECURITY;

-- 创建策略：允许所有认证用户查看所有打卡记录
CREATE POLICY "允许所有认证用户查看打卡记录"
ON public.commute_checkins
FOR SELECT
TO authenticated
USING (true);

-- 创建策略：允许所有认证用户插入打卡记录
CREATE POLICY "允许所有认证用户插入打卡记录"
ON public.commute_checkins
FOR INSERT
TO authenticated
WITH CHECK (true);

-- 创建策略：允许所有认证用户更新自己的打卡记录
CREATE POLICY "允许所有认证用户更新打卡记录"
ON public.commute_checkins
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

-- 创建策略：允许所有认证用户删除打卡记录
CREATE POLICY "允许所有认证用户删除打卡记录"
ON public.commute_checkins
FOR DELETE
TO authenticated
USING (true);
